book_list/urls.py
from django.conf.urls import url

from .views import book_list, token_verification, \
    clear_session, add_session_favorite, delete_session_favorite

urlpatterns = [
    url(r'^list$', book_list, name='book-list'),
    url(r'^token-verif$', token_verification, name='token-verif'),
    url(r'^clear-session$', clear_session, name='clear-session'),
    url(r'^add-favorite/(?P<book_id>[-\w]+)', add_session_favorite, name='add-favorite'),
    url(r'^delete-favorite/(?P<book_id>[-\w]+)', delete_session_favorite, name='delete-favorite'),
]

pepew_registration/urls.py
from django.conf.urls import url

from .views import register_page, validate_email, add_subscriber, get_subscribers, unsubscribe

urlpatterns = [
    url(r'^$', register_page, name='register'),
    url(r'^validate-email/$', validate_email, name='validate-email'),
    url(r'^add-subscriber/$', add_subscriber, name='add-subscriber'),
    url(r'^get-subscribers/$', get_subscribers, name='get-subscribers'),
    url(r'^unsubscribe/$', unsubscribe, name='unsubscribe'),
]

pepew_status/urls.py
from django.conf.urls import url

from .views import index, home2, kebakaran, berita_1, berita_2, profile, add_status, kebakaran_1, banjir_1, cuaca_ekstrim_1

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-status/$', add_status, name='add_status'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^home-2/', home2, name='home2'),
    url(r'^kebakaran/', kebakaran, name='kebakaran'),
    url(r'^berita-1/', berita_1, name='berita_1'),
    url(r'^berita-2/', berita_2, name='berita_2'),
    url(r'^kebakaran-1/', kebakaran, name='kebakaran_1'),
    
    
]

test_of_pepew/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include(('pepew_status.urls', 'status'), namespace='status')),
    url(r'^$', RedirectView.as_view(url='/profile/')),
    url(r'^profile/$', RedirectView.as_view(url='/status/profile/')),
    url(r'^saran/', include(('pepew_registration.urls', 'registration'), namespace='registration')),
   
    url(r'^home-2/',RedirectView.as_view(url='/status/home-2/')),
    url(r'^home-3/',RedirectView.as_view(url='/status/home-3/')),
    url(r'^home-4/',RedirectView.as_view(url='/status/home-4/')),
    url(r'^kebakaran/',RedirectView.as_view(url='/status/kebakaran/')),
    url(r'^berita-1/',RedirectView.as_view(url='/status/berita-1/')),
    url(r'^berita-2/',RedirectView.as_view(url='/status/berita-2/')),
    url(r'^kebakaran-1/',RedirectView.as_view(url='/status/kebakaran-1/')),
    url(r'^banjir-1/',RedirectView.as_view(url='/status/banjir-1/')),
    url(r'^cuaca-ekstrim-1/',RedirectView.as_view(url='/status/cuaca-ekstrim-1/')),
    
]

pepew_status/models.py
from django.db import models


class News_1(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)


class all_news_1(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)
class News_2(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)


class all_news_2(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)

 

pepew_status/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


from .models import News_1, all_news_1, News_2, all_news_2

response = {}


def index(request):
    response['status'] = Status.objects.all()
    response['form'] = StatusForm()
    response['username'] = []
    if 'username' in request.session.keys():
        response['username'] = request.session['username']
    html = 'index.html'
    return render(request, html, response)


def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('status:index'))
    else:
        form = StatusForm()
    return render(request, 'index.html', {'form': form,
                                          'status': Status.objects.all()})


def profile(request):
    response = {'news' : all_news_1.objects.all()}
    return render(request, 'profile.html', response)

def home2(request):
    response = {'news' : all_news_2.objects.all()}
    return render(request, 'home-2.html', response)

def kebakaran(request):
    return render(request, 'kebakaran-1.html')
def berita_1(request):
    response = {'news' : News_1.objects.all()}
    return render(request, 'all_news.html', response)
def berita_2(request):
    response = {'news' : News_2.objects.all()}
    return render(request, 'all_news_2.html', response)

def kebakaran_1(request):
    return render(request, 'kebakaran-12.html')
def banjir_1(request):
    return render(request, 'banjir-12.html')
def cuaca_ekstrim_1(request):
    return render(request, 'cuaca-ekstrim-12.html')
# def all_news(request):
     
#     return render(request, 'all_news.html', response)

pepew_status/templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="landing page">
        <meta name="google-signin-client_id" content="363267603072-umi07tav69q4ajrrir95fgsr7n50ngdt.apps.googleusercontent.com">

        <title>
            {% block title %}
                Pusat Bencana - Index
            {% endblock title %}
        </title>

        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/story_3.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Bitter|Chivo|Montserrat" rel="stylesheet">
    </head>

    <body>

        <div id="page-loading">
            <div class="loading-spinner"></div>
        </div>

        <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock content %}
        </content>

        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
            <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
            <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
            <script src="{% static 'js/story8.js' %}"></script>
            <script>
                function onSignIn(googleUser) {
                    var id_token = googleUser.getAuthResponse().id_token;
                    $.ajax({
                        url: '/book/token-verif',
                        method: 'POST',
                        dataType: 'json',
                        data: {'token': id_token},
                        success: function (result) {
                            console.log('User signed in.');
                            location.reload();
                        }
                    });
                }

                function signOut() {
                    gapi.load('auth2', function () {
                        gapi.auth2.init().then(function () {
                            var auth2 = gapi.auth2.getAuthInstance();
                            auth2.signOut().then(function () {
                                $.ajax({
                                    url: '/book/clear-session',
                                    success: function (result) {
                                        console.log('User signed out.');
                                        location.reload();
                                    }
                                });
                            });
                        });
                    });
                }
            </script>
        {% endblock scripts %}
    </body>
</html>

pepew_status/templates/layout/header.html
<!DOCTYPE html>
<html lang="en">
    <nav class="navbar navbar-expand-lg main-navbar">
        <a class="navbar-brand navbar-button" href="{% url 'status:profile' %}">Profile</a>
		<a class="navbar-brand navbar-button" href="{% url 'status:index' %}">Saran</a>
        <a class="navbar-brand navbar-button" href="{% url 'book-list:book-list' %}">Berita</a>
        <a class="navbar-brand navbar-button" href="{% url 'registration:register' %}">Komentar</a>
        <select class="select-theme"></select>
        <button class="apply-theme btn" style="margin: 10px">Select Theme</button>
        {% if not username %}
            <div class="g-signin2" data-onsuccess="onSignIn"></div>
        {% else %}
            <button class="btn btn-danger" onclick="signOut();">Sign out</button>
        {% endif %}
    </nav>
</html>