book_list/urls.py
from django.conf.urls import url

from .views import book_list, token_verification, \
    clear_session, add_session_favorite, delete_session_favorite

urlpatterns = [
    url(r'^list$', book_list, name='book-list'),
    url(r'^token-verif$', token_verification, name='token-verif'),
    url(r'^clear-session$', clear_session, name='clear-session'),
    url(r'^add-favorite/(?P<book_id>[-\w]+)', add_session_favorite, name='add-favorite'),
    url(r'^delete-favorite/(?P<book_id>[-\w]+)', delete_session_favorite, name='delete-favorite'),
]

pepew_status/urls.py
from django.conf.urls import url

from .views import index, home2, kebakaran, berita_1, berita_2, profile, add_status, kebakaran_1, banjir_1, cuaca_ekstrim_1

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-status/$', add_status, name='add_status'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^home-2/', home2, name='home2'),
    url(r'^kebakaran/', kebakaran, name='kebakaran'),
    url(r'^berita-1/', berita_1, name='berita_1'),
    url(r'^berita-2/', berita_2, name='berita_2'),
    url(r'^kebakaran-1/', kebakaran, name='kebakaran_1'),
    
    
]

test_of_pepew/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include(('pepew_status.urls', 'status'), namespace='status')),
    url(r'^$', RedirectView.as_view(url='/profile/')),
    url(r'^profile/$', RedirectView.as_view(url='/status/profile/')),
    url(r'^saran/', include(('pepew_registration.urls', 'registration'), namespace='registration')),
   
    url(r'^home-2/',RedirectView.as_view(url='/status/home-2/')),
    url(r'^home-3/',RedirectView.as_view(url='/status/home-3/')),
    url(r'^home-4/',RedirectView.as_view(url='/status/home-4/')),
    url(r'^kebakaran/',RedirectView.as_view(url='/status/kebakaran/')),
    url(r'^berita-1/',RedirectView.as_view(url='/status/berita-1/')),
    url(r'^berita-2/',RedirectView.as_view(url='/status/berita-2/')),
    url(r'^kebakaran-1/',RedirectView.as_view(url='/status/kebakaran-1/')),
    url(r'^banjir-1/',RedirectView.as_view(url='/status/banjir-1/')),
    url(r'^cuaca-ekstrim-1/',RedirectView.as_view(url='/status/cuaca-ekstrim-1/')),
    
]

pepew_status/models.py
from django.db import models


class News_1(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)


class all_news_1(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)
class News_2(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)


class all_news_2(models.Model):
    title = models.CharField(max_length = 200,default="", editable=True)
    image = models.URLField(max_length = 200, blank = True, null =True, default="", editable=True)
    news = models.TextField(default="", editable=True)

 

pepew_status/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


from .models import News_1, all_news_1, News_2, all_news_2

response = {}


def index(request):
    response['status'] = Status.objects.all()
    response['form'] = StatusForm()
    response['username'] = []
    if 'username' in request.session.keys():
        response['username'] = request.session['username']
    html = 'index.html'
    return render(request, html, response)


def add_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('status:index'))
    else:
        form = StatusForm()
    return render(request, 'index.html', {'form': form,
                                          'status': Status.objects.all()})


def profile(request):
    response = {'news' : all_news_1.objects.all()}
    return render(request, 'profile.html', response)

def home2(request):
    response = {'news' : all_news_2.objects.all()}
    return render(request, 'home-2.html', response)

def kebakaran(request):
    return render(request, 'kebakaran-1.html')
def berita_1(request):
    response = {'news' : News_1.objects.all()}
    return render(request, 'all_news.html', response)
def berita_2(request):
    response = {'news' : News_2.objects.all()}
    return render(request, 'all_news_2.html', response)

def kebakaran_1(request):
    return render(request, 'kebakaran-12.html')
def banjir_1(request):
    return render(request, 'banjir-12.html')
def cuaca_ekstrim_1(request):
    return render(request, 'cuaca-ekstrim-12.html')
# def all_news(request):
     
#     return render(request, 'all_news.html', response)

pepew_status/templates/index.html
{% extends 'layout/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% block content %}
        <div class="main-div">
            <div class="jumbotron">
                <div class="container-fluid">
                    <h1 class="page-header">Hello apa kabar?</h1>
                </div>
            </div>

            <div class="container mx-auto d-block">
                <form class="form-block" action="{% url 'status:add_status' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form }}
                    </div>
                    <button type="submit" class="btn btn-primary" id="status-submit-button">Input Status</button>
                </form>
            </div>

            <div class="container mx-auto d-block">
                {% if status %}
                    <table class="table table-hover table-striped table-dark" align="center" style="text-align: center">
                        <thead>
                            <tr>
                                <th scope="col">Status</th>
                                <th scope="col">Waktu Pembuatan</th>
                            </tr>
                        </thead>
                        {% for data in status %}
                        <tr>
                            <td scope="row" id="status-col-status">{{ data.status }}</td>
                            <td scope="row" id="status-col-created-at">{{ data.created_at|date:"l" }}, {{ data.created_at }}</td>
                        </tr>
                    {% endfor %}
                    </table>
                {% else %}
                    <h1 class="text-main">Tidak Ada Status</h1>
                {% endif %}
            </div>
        </div>
    {% endblock %}
</html>